import { notFound } from 'next/navigation';
import { projects } from '../../projects';
import { quoteAnnotations } from '../../quote-annotations';
export function generateStaticParams() { return projects.map(p => ({slug:p.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) {const {slug}=await params;const p=projects.find(p=>p.slug===slug);return {title:p ? `${p.focus} — Benji Kim`:'Project not found — Benji Kim',description:p?.detail};}
export default async function Project({params}:{params:Promise<{slug:string}>}) {
 const {slug}=await params; const p=projects.find(p=>p.slug===slug); if(!p)notFound();
 return <main className="portfolio detail">
  <header className="detail-header"><a href="/">Benji Kim</a><nav aria-label="Main navigation"><a href="/#work">work</a><a href="/#about-me">about me</a><a href="/#contact">contact</a></nav></header>
  <article><h1>{p.focus}</h1><p className="lead">{p.detail}</p><p className="role">Role: User Research, Design</p>
  <figure className="detail-figure"><img src={p.image} width={p.width ?? 1247} height={p.height} alt={p.alt}/></figure>
  <section className="detail-copy"><h2>The interface</h2><ul>{p.notes.map(note=><li key={note}>{note}</li>)}</ul></section>
  {slug === 'travel-insurance' && <section className="quote-designs" aria-label="Quote form designs">
    <section className="quote-design"><h2>Desktop quote form</h2><p className="design-description">Trip details, traveler information, and trip cost coverage — including completed fields, multiple travelers, and validation states.</p><div className="annotated-design"><figure><a href="/images/quote-desktop-full.png?v=2" target="_blank" rel="noreferrer" aria-label="Open desktop quote form states at full size"><img src="/images/quote-desktop.png?v=2" width="1410" height="3890" loading="lazy" alt="Thirteen desktop quote form states showing empty, completed, and required-field error views across all three steps, plus U.S. destinations, four travelers, non-U.S. residence, and optional trip cost coverage."/></a><figcaption><a href="/images/quote-desktop-full.png?v=2" target="_blank" rel="noreferrer">View full-size desktop designs ↗</a></figcaption></figure><aside className="design-notes" aria-label="Desktop design annotations"><h3 className="notes-heading">Design annotations</h3>{quoteAnnotations.slice(0, 11).map(([title, text], index) => <article key={title} className="annotation"><h4><span>{String(index + 1).padStart(2, '0')}</span> {title}</h4><p>{text}</p></article>)}</aside></div></section>
    <section className="quote-design"><h2>Mobile quote form</h2><p className="design-description">The trip details step on mobile, with destination and travel dates in a single-column layout.</p><div className="annotated-design annotated-mobile"><figure className="mobile-design"><a href="/images/quote-mobile.png" target="_blank" rel="noreferrer" aria-label="Open mobile quote form at full size"><img src="/images/quote-mobile.png" width="400" height="779" loading="lazy" alt="Mobile travel insurance hero with a three-step quote form, destination field, travel dates, and Next step button."/></a><figcaption><a href="/images/quote-mobile.png" target="_blank" rel="noreferrer">View full-size mobile design ↗</a></figcaption></figure><aside className="design-notes" aria-label="Mobile design annotation"><h3 className="notes-heading">Design annotation</h3><article className="annotation"><h4><span>12</span> {quoteAnnotations[11][0]}</h4><p>{quoteAnnotations[11][1]}</p></article></aside></div></section>
  </section>}
  {slug === 'plan-comparison' && <section className="results-videos" aria-label="Quote results walkthroughs">
    <section className="video-row"><video controls autoPlay={false} playsInline preload="metadata" poster="/images/quote-results-poster.jpg" aria-label="Quote results walkthrough" aria-describedby="results-description"><source src="/videos/quote-results.mp4" type="video/mp4"/><a href="/videos/quote-results.mp4">Download the quote results video</a></video><aside className="video-description" id="results-description"><h2>Quote results</h2><p>Explore travel insurance plans with trip details, coverage filters, and prices in one view.</p><p>Each plan card brings together ratings, key benefits, and actions to compare plans or review their details.</p></aside></section>
    <section className="video-row"><video controls autoPlay={false} playsInline preload="metadata" poster="/images/quote-results-updated-poster.jpg" aria-label="Plan comparison walkthrough" aria-describedby="compare-description"><source src="/videos/quote-results-updated.mp4" type="video/mp4"/><a href="/videos/quote-results-updated.mp4">Download the plan comparison video</a></video><aside className="video-description" id="compare-description"><h2>Compare plans</h2><p>Review selected plans side by side, with prices and selection actions at the top of each column.</p><p>Aligned rows organize plan summaries, medical benefits, and trip protection, making differences in coverage easier to find.</p></aside></section>
  </section>}
  <p className="detail-back"><a href="/#work">← back to work</a></p></article>
  <footer><p>based in NYC.</p><p><a href="mailto:benjikim@gmail.com">benjikim@gmail.com</a> / <a href="/documents/resume_2026.pdf" target="_blank" rel="noreferrer">resume</a> / <a className="phone" href="tel:+16466206406">646 620 6406</a></p></footer>
 </main>;
}
